export { default as Agentation } from './element-source-inspector.svelte';
export { default as AgentationInspector } from './element-source-inspector.svelte';
export { default as ElementSourceInspector } from './element-source-inspector.svelte';
export {
	AGENTATION_ACTIVE_CHANGE_EVENT,
	AGENTATION_BLOCKED_INTERACTION_EVENT,
	COPY_OPEN_ACTIVE_CHANGE_EVENT,
	COPY_OPEN_BLOCKED_INTERACTION_EVENT,
	INSPECTOR_ACTIVE_CHANGE_EVENT,
	INSPECTOR_BLOCKED_INTERACTION_EVENT
} from './events';
export type {
	AbsoluteRectBox,
	AgentationAnnotationSnapshot,
	AgentationExportPayload,
	AnnotationBoundingBox,
	AnnotationCapture,
	AnnotationComponentContext,
	AnnotationElementSnapshot,
	AnnotationPageSnapshot,
	AnnotationPosition,
	AreaSelectionAnchor,
	AreaInspectorNote,
	ComponentContextMode,
	ComputedStyleSnapshot,
	DragSelectionState,
	ElementNoteAnchor,
	ElementInspectorNote,
	GroupInspectorNote,
	GroupSelectionAnchor,
	GroupSelectionPreviewState,
	InspectorHoverInfo,
	InspectorNoteAnchor,
	InspectorNoteKind,
	InspectorNote,
	InspectorPosition,
	InspectorProps as AgentationProps,
	InspectorProps as AgentationInspectorProps,
	InspectorProps,
	InspectorRuntimeOptions,
	NoteMarkerFallback,
	NoteResolutionState,
	NoteSourceInfo,
	NoteComposerState,
	NotesSettings,
	OutputMode,
	RectBox,
	RenderedInspectorNote,
	ResolvedNotePosition,
	TextInspectorNote,
	TextSelectionAnchor,
	ToolbarCoordinates,
	ToolbarState,
	VsCodeScheme
} from './types';
export type { InspectorActiveChangeDetail, InspectorBlockedInteractionDetail } from './events';
